# docker-compose.yml (루트)
version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: brainshare
      POSTGRES_USER: brain
      POSTGRES_PASSWORD: pass
    ports: ["5432:5432"]
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      # DATABASE_URL: postgresql+asyncpg://brain:pass@db:5432/brainshare
      DATABASE_URL: postgresql+asyncpg://brain:pass@localhost:5432/brainshare
    depends_on: [db]
    ports: ["8000:8000"]
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on: [backend]
    ports: ["3000:3000"]
