# docker-compose.yml (루트)
version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: brainshare
      POSTGRES_USER: brain
      POSTGRES_PASSWORD: pass
    ports: ["5432:5432"]
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      # DATABASE_URL: postgresql+asyncpg://brain:pass@db:5432/brainshare
      DATABASE_URL: postgresql+asyncpg://brain:pass@db:5432/brainshare
    depends_on: [db]
    ports: ["8000:8000"]
    volumes:
      - ./backend/app:/app/app
    # command: poetry run uvicorn app.main:app --host 0.0.0.0 --reload
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on: [backend]
    ports: ["3000:3000"]
    volumes:
    - ./frontend:/app
    - /app/node_modules  # 중요: node_modules는 호스트와 충돌 방지용으로 제외
    environment:
      - CHOKIDAR_USEPOLLING=true  # Vite, Next 등 핫 리로드 문제 해결

